### ISSUE TITLE
description of sites included in list?

### ISSUE THREAD

**Issue by nicoleahmed** [nonPointer/uBlacklist-Subscription#3]
Hi this list looks comprehensive, thanks for maintaining

What are the criteria for sites being added to this list? And is there any overlap  with other subscriptions lists?

Thank you :)

**Comment by nonPointer** [comment]
A1: Sites that have been classified as a content farm, search results page, lottery, blackhat SEO.
A2: Yes, of course.

**Comment by nicoleahmed** [comment]
Thanks for answering :)
