### ISSUE TITLE
希望解除对这个网站的拦截

### ISSUE THREAD

**Issue by Stab** [nonPointer/uBlacklist-Subscription#4]
这个网站是搬运某论坛的帖子（原站很多帖子有权限，只有高等级的会员才能查看），希望解除对这个网站的拦截
![image](https://user-images.githubusercontent.com/76845571/192204628-ba809b2c-8778-4044-b1d1-17d5ae694dc6.png)

**Comment by nonPointer** [comment]
如有需要可以自行添加至本地白名单。
